# Generated by Django 5.1.11 on 2025-08-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealslist',
            name='external_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
