# Generated by Django 5.1.11 on 2025-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0002_dealslist_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Manuale'), ('automatic', 'Automatica'), ('scheduled', 'Programmata')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Successo'), ('failed', 'Fallita'), ('partial', 'Parziale')], max_length=20)),
                ('deals_created', models.IntegerField(default=0)),
                ('deals_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
