# Generated by Django 5.1.11 on 2025-08-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0003_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealslist',
            name='deal_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
