# Generated by Django 5.1.11 on 2025-08-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0004_dealslist_deal_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealslist',
            name='deal_rating',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
    ]
