# Generated by Django 5.1.11 on 2025-08-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0005_alter_dealslist_deal_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealslist',
            name='normal_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dealslist',
            name='sale_price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
