# Generated by Django 5.1.11 on 2025-08-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0006_alter_dealslist_normal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealslist',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dealslist',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
