# Generated by Django 5.1.11 on 2025-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0007_alter_dealslist_normal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealslist',
            name='store_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
