# Generated by Django 5.1.11 on 2025-09-01 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0008_dealslist_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealslist',
            name='store_name',
        ),
        migrations.AddField(
            model_name='dealslist',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamedeals.storeinfo'),
        ),
    ]
