# Generated by Django 5.1.11 on 2025-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0009_remove_dealslist_store_name_dealslist_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='store_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
