# Generated by Django 5.1.11 on 2025-09-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0010_alter_storeinfo_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='store_banner_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='store_icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='store_logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
