# Generated by Django 5.1.11 on 2025-09-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0011_storeinfo_store_banner_url_storeinfo_store_icon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealslist',
            name='saving',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
