# Generated by Django 5.1.11 on 2025-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0012_dealslist_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealslist',
            name='rating_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dealslist',
            name='release_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
