# Generated by Django 5.1.11 on 2025-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0013_dealslist_rating_text_dealslist_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealslist',
            name='rating_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dealslist',
            name='release_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
