# Generated by Django 5.1.11 on 2025-09-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0014_alter_dealslist_rating_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealslist',
            name='release_date',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
