# Generated by Django 5.1.11 on 2025-09-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedeals', '0015_alter_dealslist_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealslist',
            name='deal_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
